---
version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "kernelsam"
    cooldown:
      default-days: 21
      exclude:
        - "senzing-factory/*"
    directory: "/"
    groups:
      senzing-factory:
        patterns:
          - "senzing-factory/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    assignees:
      - "arawinters"
    cooldown:
      default-days: 21
    directory: "/"
    allow:
      - dependency-type: "indirect"
      - dependency-type: "direct"
    ignore:
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/*"
      - dependency-name: "rxjs"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sass"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tslib"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ng-packagr"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ts-node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "monthly"
